name: soru
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # state management
  stacked: ^1.5.8
  # navigation
  auto_route: ^0.5.0
  stacked_services: ^0.3.4
  # inversion of control
  get_it: ^4.0.2
  email_validator: ^1.0.4
  # http request
  http: ^0.12.0+2
  # async package to add additional Cancellable operations
  async: ^2.0.8
  image_picker: 0.6.3
  # firebase
  firebase_auth: 0.15.4
  cloud_firestore: ^0.13.0+1
  cached_network_image: ^2.0.0-rc
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.5
  firebase_analytics: ^5.0.11
  firebase_dynamic_links: ^0.5.0+11
  firebase_remote_config: ^0.3.0+3

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/google_signin_button.png

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
